### ISSUE TITLE
병실 API 개발

### ISSUE THREAD

**Issue by amaran-th** [Effective-2024/Effective-Detector-BE#14]
- 병실 생성 API
대충 병실 명칭만 전달받으면 될듯
![image](https://github.com/user-attachments/assets/c94c48b5-4e71-4cdd-ae44-adeb77367f67)

(근데 병실별 카메라 연결은 어떻게 함...??)

- 병실 목록 조회 API
병실 순서는 이름순으로 정렬

**Comment by shkisme** [comment]
MVP 이후로 미룸.
